Hw04 lru cache
mrkucher83/hw_test pull request #4
Opened 2021-04-07 16:29 UTC by mrkucher83

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-04-08 05:51 UTC, kulti requested changes
Александр, получилось хорошее решение. В коде есть шерховатости, которые не влияют на работоспособность (1 балл за чистоту кода).

Не хватает тестов. Для списка расширен тест complex, но новых тестов нет (не могу тут баллы добавить). Для кэша написан только один тест, хотя в задании предложено два варианта логики, которую нужно протестировать (тут только 1 балл).

Итого — 6 баллов. Пока незачет.

Если есть сложности с придумыванием тестов, то самое время потренировать этот навык.
- Посмотрите слайд про мышление тестировщика из первого занятия про тестирования. Подумайте над этими вопросами.
- Запустите тестирование мутированием. Подумайте, что за бизнес-кейсы скрываются за непротестированным поведением.

2021-04-08 05:51 UTC, kulti commented on hw04_lru_cache/list.go
> +	}
По моему 2 строчки из трех в каждой ветке этого if'a одинаковые. Почему бы их не вынести из условия?

2021-04-08 05:51 UTC, kulti commented on hw04_lru_cache/list.go
> +		log.Println("no items to remove")
Рекомендую перечитывать задание после выполнения. Некоторые вещи мы замечаем не сразу, т.к. они в тот момент были не нужны или не имели для нас смысла. Например:
> Гарантируется, что методы Remove и MoveToFront вызываются от существующих в списке элементов.

PS. Логирование внутри типа-контейнера обычно так себе идея. Обычно логирование происходит на уровне приложения, а всякие другие методы просто возвращают ошибки.

2021-04-08 05:51 UTC, kulti commented on hw04_lru_cache/cache.go
> +	l.items = nil
А почему с l.queue не очищается?

2021-04-08 05:51 UTC, kulti commented on hw04_lru_cache/cache.go
> +		l.items[key].Value = cacheItem{string(key), value}
А зачем полностью новый cacheItem создавать? Вроде, можно просто значение поменять.

2021-04-08 05:51 UTC, kulti commented on hw04_lru_cache/cache.go
> +		if rmKey, ok := l.queue.Back().Value.(cacheItem); ok {
Интересно, почему тут сделан тайп-ассерт безопасный (с ok), а в остальных случаях нет?

Предлагаю подумать, нужно ли переживать, что в список может попасть не cacheItem? Если не нужно, то, очевидно, тайп-ассерт тоже не нужен. Если да, то какое поведение должно быть, если там что-то не то?

2021-04-08 06:56 UTC, mrkucher83 commented on hw04_lru_cache/list.go
> +	}
Fixed

2021-04-08 06:56 UTC, mrkucher83 commented on hw04_lru_cache/cache.go
> +	l.items = nil
Fixed

2021-04-08 06:57 UTC, mrkucher83 commented on hw04_lru_cache/cache.go
> +		l.items[key].Value = cacheItem{string(key), value}
Fixed

2021-04-08 07:06 UTC, mrkucher83 commented on hw04_lru_cache/cache.go
> +		if rmKey, ok := l.queue.Back().Value.(cacheItem); ok {
Согласен. Единственный вариант записать в очередь - метод Set(), который делает это через создание экземпляра cacheItem. Другого типа там быть не может.

2021-04-08 12:57 UTC, mrkucher83 commented on hw04_lru_cache/list.go
> +		log.Println("no items to remove")
Тут я убрал логи, но не понимаю, нужно ли еще что-то делать.

2021-04-08 13:01 UTC, mrkucher83 commented on hw04_lru_cache/cache.go
> +		l.items[key].Value = cacheItem{string(key), value}
Пытался изменить значение cacheItem.value вместо создания нового cacheItem, но это не работает. Еще думаю.
`item := l.items[key].Value.(cacheItem)
item.value = value`

2021-04-09 05:57 UTC, kulti commented on hw04_lru_cache/list.go
> +		log.Println("no items to remove")
Задам вопрос по другому. Зачем нужен `if l.CountItems == 0`?

2021-04-09 06:01 UTC, kulti commented on hw04_lru_cache/list.go
> +	}
Я написал про две строчки, а вынесена только одна. Если непонятно, какие две строчки имелись в виду, то всегда можно спросить :)

Я писал про `front = &ListItem{v, l.FrontItem, nil}`.

2021-04-09 06:03 UTC, kulti commented on hw04_lru_cache/cache.go
> +		l.items[key].Value = cacheItem{string(key), value}
Я понял. Это потому что хранится cacheItem, а не указатель на cacheItem. Тогда да, вариант только один — создавать новый cacheItem.

2021-04-09 06:05 UTC, kulti commented on hw04_lru_cache/cache.go
> +	}
Можно было просто `l.queue = NewList()`. Удаление элементов по одному лишь сохраняет изначальный объект List, но при этом кучу лишней работы делает.

2021-04-09 06:06 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +		_ = c.Set("bbb", 200) // rarely used item
Это не редко используемые элемент. Здесь тоже самое происходит, что и в purge logic. bbb добавили первым и первым же вытолкнули, как только положили 3 новых элемента.

2021-04-09 06:09 UTC, kulti approved these changes
Код все еще не очень чистый и есть странные места. Зато появились новые тесты.

ДЗ принято на 8/10.

2021-04-09 06:09 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +	t.Run("clear test", func(t *testing.T) {
👍

2021-04-09 06:09 UTC, kulti commented on hw04_lru_cache/list_test.go
> +	t.Run("different values", func(t *testing.T) {
Наверно, different types? Отличный тест на «странное» использование 👍

2021-04-09 06:33 UTC, mrkucher83 commented on hw04_lru_cache/list.go
> +	}
Исправлено.

2021-04-09 06:43 UTC, mrkucher83 commented on hw04_lru_cache/list.go
> +		log.Println("no items to remove")
Не нужен, убрал.

2021-04-09 06:46 UTC, mrkucher83 commented on hw04_lru_cache/cache.go
> +	}
Исправлено.

2021-04-09 06:51 UTC, mrkucher83 commented on hw04_lru_cache/cache_test.go
> +		_ = c.Set("bbb", 200) // rarely used item
Немного подправил порядок вызова элементов  - тест проходит.

2021-04-09 06:56 UTC, mrkucher83 commented on hw04_lru_cache/cache_test.go
> +	t.Run("clear test", func(t *testing.T) {
Иногда полезно запускать отчет о покрытии тестами)

2021-04-09 07:03 UTC, merged