HW7 is completed without progress bar
mrkucher83/hw_test pull request #7
Opened 2021-05-12 09:40 UTC by mrkucher83

## Домашнее задание №7 «Утилита для копирования файлов»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-05-12 16:29 UTC, kulti requested changes
В решении не хватает прогресс-бара:
> Также необходимо выводить в консоль прогресс копирования в процентах (%), допускается использовать для этого стороннюю библиотеку.

И есть проблемы в логике работы.

2021-05-12 16:29 UTC, kulti commented on hw07_file_copying/main.go
> +		return
Если была ошибка, то хорошо бы выйти с кодом 1 — `os.Exit(1)`

2021-05-12 16:29 UTC, kulti commented on hw07_file_copying/copy.go
> +	if finfo.Size() == 0 && finfo.Name() == "urandom" {
/dev/urandom —  это один из примеров файлов без длинны. Их много разных существует.

Корректнее будет использовать проверку на isRegular.

2021-05-12 16:29 UTC, kulti commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
limit приходит от пользователя и может принимать любые значения. В каких случаях этой проверки будет недостаточно, чтобы все хорошо было?

2021-05-12 16:29 UTC, kulti commented on hw07_file_copying/copy.go
> +	tmpfile, err := os.CreateTemp("testdata", "tmpFile.txt")
А зачем тут временный файл?

2021-05-12 16:29 UTC, kulti commented on hw07_file_copying/copy.go
> +	buffer := make([]byte, limit+offset)
Какие реальные значения может принимать limit? Какие проблемы тут могут возникнуть?

2021-05-13 07:22 UTC, mrkucher83 commented on hw07_file_copying/main.go
> +		return
Исправлено.

2021-05-13 07:22 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	if finfo.Size() == 0 && finfo.Name() == "urandom" {
Исправлено.

2021-05-13 07:24 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
Добавил проверку лимита на отрицательное или превышающее размер файла значение для оптимизации памяти.

2021-05-13 07:25 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	tmpfile, err := os.CreateTemp("testdata", "tmpFile.txt")
По этому вопросу изначально у меня были сомнения (неправильно интерпретировал подсказки))). Избавился от временного файла и код сильно сократился.)

2021-05-13 07:30 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	buffer := make([]byte, limit+offset)
Здесь пока в раздумьях - перед тем как попасть в readOffset я проверил limit на пограничные значения и оптимизировал.

2021-05-13 15:43 UTC, kulti commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
Да, стало лучше, но еще не совсем хорошо. Какую идею выражает newLimit? Это ведь количество байт, которое будет прочитано, да? Тогда не очень понимаю логику этой проверки:
```
if newLimit > finfo.Size() {
	newLimit = finfo.Size() - offset
}
```

2021-05-13 15:46 UTC, kulti requested changes

2021-05-13 15:46 UTC, kulti commented on hw07_file_copying/copy.go
> +	return buffer[offset:n], nil
А зачем читать лишний байты из файла, если они не нужны?

2021-05-13 15:46 UTC, kulti commented on hw07_file_copying/copy.go
> +	buffer := make([]byte, limit+offset)
Т.е. сейчас limit может быть от 0 до размера файла. Какие-нибудь значения из этого диапазона могут стать проблемой? Если да, то какие? Если нет, то почему?

2021-05-13 15:53 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
newLimit используется в функции readOffset и используется для создания буфера байтов. Данная проверка служит для оптимизации памяти при создании буфера, если при файле в 100 байт пользователь введет limit на 1 млн.

2021-05-13 16:25 UTC, kulti commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
Ага, похоже на проверку максимального значения. И вот это мне как раз и непонятно — сравниваем с одним, а присваиваем что-то другое. Тут явно что-то не так :)

2021-05-15 12:27 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	buffer := make([]byte, limit+offset)
Исправлено.

2021-05-15 12:28 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	if newLimit == 0 {
Исправлено.

2021-05-15 12:28 UTC, mrkucher83 commented on hw07_file_copying/copy.go
> +	return buffer[offset:n], nil
Исправлено.

2021-05-17 05:08 UTC, kulti approved these changes
ДЗ принято — 10/10 🎉

2021-05-17 07:24 UTC, merged